#!/bin/bash


BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAKENES_SCRIPT=make_nes.sh

#compress tables
#cd romdata
#./nam/make_nm.bat
#cd ..


#build and apply tools
g++ "$BASEDIR/tools/jumpbeats_finalpass.cpp" -o /tmp/jumpbeats_finalpass
/tmp/jumpbeats_finalpass "$BASEDIR/romdata/first_stage_beats.src2" "$BASEDIR/romdata/first_stage_beats.s" "$BASEDIR/romdata/charlist" "$BASEDIR/romdata/first_stage_beats.inc"
/tmp/jumpbeats_finalpass "$BASEDIR/romdata/second_stage_beats.src2" "$BASEDIR/romdata/second_stage_beats.s" "$BASEDIR/romdata/charlist" "$BASEDIR/romdata/second_stage_beats.inc"
/tmp/jumpbeats_finalpass "$BASEDIR/romdata/third_stage_beats.src2" "$BASEDIR/romdata/third_stage_beats.s" "$BASEDIR/romdata/charlist" "$BASEDIR/romdata/third_stage_beats.inc"

g++ "$BASEDIR/tools/cutscenes.cpp" -o /tmp/cutscenes
/tmp/cutscenes "$BASEDIR/romdata/cutscenes.src" "$BASEDIR/romdata/charlist" "$BASEDIR/romdata/cutscenes.s"

#build

"$BASEDIR/$MAKENES_SCRIPT" utaco "$BASEDIR/utaco.cfg" "$BASEDIR/utaco.map" "$BASEDIR" "$BASEDIR/src" "-I $BASEDIR -I $BASEDIR/src/nsfd_v26 -g " "--dbgfile utaco.nes.dbg.org" "nsfd_v26/driver.s utaco.s songdata_1.s songdata_2.s songdata_3.s minisongs.s"


#replace paths on debug info for windows
sed -e 's/\/mnt\/ntfs_e\/projects\/nes\/utaco//g' -e 's/\//\\/g' utaco.nes.dbg.org > utaco.nes.dbg


#Attach chr roms
cat "$BASEDIR/romdata/banks_0.chr" >> "$BASEDIR/utaco.nes"
cat "$BASEDIR/romdata/banks_1.chr" >> "$BASEDIR/utaco.nes"
cat "$BASEDIR/romdata/banks_2.chr" >> "$BASEDIR/utaco.nes"
cat "$BASEDIR/romdata/banks_3.chr" >> "$BASEDIR/utaco.nes"

